/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package hipits.com;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int checkable=0x7f010000;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int btnAdd=0x7f060010;
        public static final int btnDelete=0x7f060011;
        public static final int btnSearch=0x7f06000f;
        public static final int check=0x7f060005;
        public static final int checkliner=0x7f060006;
        public static final int graph=0x7f06000e;
        public static final int graph1=0x7f060000;
        public static final int graph2=0x7f060001;
        public static final int img=0x7f060007;
        public static final int layout=0x7f060002;
        public static final int listView_list=0x7f060014;
        public static final int listview=0x7f060012;
        public static final int nameinsert=0x7f060017;
        public static final int spinner_select=0x7f060013;
        public static final int spinnersort_text1=0x7f060015;
        public static final int spinnersort_text2=0x7f060016;
        public static final int summary=0x7f060009;
        public static final int textView1=0x7f060003;
        public static final int textView2=0x7f060004;
        public static final int textView_date=0x7f06000c;
        public static final int textView_massage=0x7f06000d;
        public static final int textView_name=0x7f06000a;
        public static final int textView_number=0x7f06000b;
        public static final int title=0x7f060008;
    }
    public static final class layout {
        public static final int graph=0x7f030000;
        public static final int main=0x7f030001;
        public static final int my_list_item3=0x7f030002;
        public static final int numberinfomation=0x7f030003;
        public static final int numberlist=0x7f030004;
        public static final int spinnersort=0x7f030005;
        public static final int spinnersorttext=0x7f030006;
    }
    public static final class menu {
        public static final int menu=0x7f050000;
    }
    public static final class string {
        public static final int alert_msg_exit=0x7f040004;
        public static final int app_name=0x7f040001;
        public static final int button_no=0x7f040003;
        public static final int button_yes=0x7f040002;
        public static final int hello=0x7f040000;
    }
    public static final class styleable {
        /** Attributes that can be used with a CheckableRealtiveLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CheckableRealtiveLayout_checkable hipits.com:checkable}</code></td><td></td></tr>
           </table>
           @see #CheckableRealtiveLayout_checkable
         */
        public static final int[] CheckableRealtiveLayout = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link hipits.com.R.attr#checkable}
          attribute's value can be found in the {@link #CheckableRealtiveLayout} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:checkable
        */
        public static final int CheckableRealtiveLayout_checkable = 0;
    };
}
